export enum UserRole {
  ADMIN = 'ADMIN',
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  RESPONSIBLE = 'RESPONSIBLE',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  TUTOR_GROUP = 'TUTOR_GROUP',
  CONCIERGE = 'CONCIERGE',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
}
